// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX8QX9qZvijdk3L_RT8kuLEeZ59m1n54I',
    appId: '1:1037333979588:web:29099c41d8ebdcc2488491',
    messagingSenderId: '1037333979588',
    projectId: 'accountabilibuddies-ff638',
    authDomain: 'accountabilibuddies-ff638.firebaseapp.com',
    storageBucket: 'accountabilibuddies-ff638.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX8QX9qZvijdk3L_RT8kuLEeZ59m1n54I',
    appId: '1:1037333979588:android:4882a01516fa1206488491',
    messagingSenderId: '1037333979588',
    projectId: 'accountabilibuddies-ff638',
    storageBucket: 'accountabilibuddies-ff638.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX8QX9qZvijdk3L_RT8kuLEeZ59m1n54I',
    appId: '1:1037333979588:ios:ae356ea6f55e4b83488491',
    messagingSenderId: '1037333979588',
    projectId: 'accountabilibuddies-ff638',
    storageBucket: 'accountabilibuddies-ff638.firebasestorage.app',
  );
}
